# Generated by Django 6.0.2 on 2026-05-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_support_thread_user_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderParticipant',
        ),
    ]
