# Generated by Django 6.0.2 on 2026-02-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_vehicle_and_product_compatibility_seed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'model', 'generation', 'body_type'], name='veh_brand_model_gen_idx'),
        ),
    ]
