# Generated by Django 6.0.2 on 2026-03-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_vehicle_hierarchy_bodytype_compat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='name',
            field=models.CharField(choices=[('SEDAN', 'Седан'), ('HATCHBACK', 'Хэтчбек'), ('LIFTBACK', 'Лифтбек'), ('WAGON', 'Универсал'), ('SUV', 'Кроссовер / SUV'), ('COUPE', 'Купе'), ('CABRIO', 'Кабриолет'), ('MINIVAN', 'Минивэн'), ('PICKUP', 'Пикап'), ('VAN', 'Фургон')], max_length=100),
        ),
    ]
