# Generated by Django 6.0.2 on 2026-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_bodytype_name_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='name',
            field=models.CharField(choices=[('SEDAN', 'Седан'), ('LIFTBACK', 'Лифтбек'), ('HATCHBACK_3D', 'Хэтчбек 3дв'), ('HATCHBACK_5D', 'Хэтчбек 5дв'), ('SUV_3D', 'Внедорожник 3дв'), ('SUV_5D', 'Внедорожник 5дв'), ('WAGON', 'Универсал'), ('COUPE', 'Купе'), ('CABRIO', 'Кабриолет'), ('MINIVAN', 'Минивэн'), ('PICKUP', 'Пикап'), ('VAN', 'Фургон'), ('LIMOUSINE', 'Лимузин')], max_length=100),
        ),
    ]
