# Generated by Cursor on 2026-03-16

from django.db import migrations


def forwards(apps, schema_editor):
    BodyType = apps.get_model("catalog", "BodyType")

    # Old codes from previous enum versions -> new, more specific defaults.
    BodyType.objects.filter(name="HATCHBACK").update(name="HATCHBACK_5D")
    BodyType.objects.filter(name="SUV").update(name="SUV_5D")


def backwards(apps, schema_editor):
    BodyType = apps.get_model("catalog", "BodyType")

    # Best-effort revert.
    BodyType.objects.filter(name="HATCHBACK_5D").update(name="HATCHBACK")
    BodyType.objects.filter(name="SUV_5D").update(name="SUV")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_bodytype_name"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

