# Generated by Django 6.0.2 on 2026-03-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_bodytype_migrate_old_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_code', models.CharField(max_length=64)),
                ('transmission_code', models.CharField(max_length=64)),
                ('transmission_type', models.CharField(choices=[('MT', 'Механика'), ('AT', 'Автомат'), ('CVT', 'Вариатор'), ('DCT', 'Робот (DCT)'), ('ROBOT', 'Робот')], max_length=16)),
                ('gears', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power_hp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('torque_nm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_variants', to='catalog.generation')),
            ],
            options={
                'ordering': ['generation', 'engine_code', 'transmission_type', 'transmission_code'],
                'constraints': [models.UniqueConstraint(fields=('generation', 'engine_code', 'transmission_code'), name='techvariant_generation_engine_transmission_unique')],
            },
        ),
    ]
