# Generated by Django 6.0.2 on 2026-03-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_techvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compatibility_mode',
            field=models.CharField(choices=[('BODY_TYPE', 'Кузов'), ('TECH_VARIANT', 'Техника')], default='BODY_TYPE', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductTechVariantCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_variant_compatibilities', to='catalog.product')),
                ('tech_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='catalog.techvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'tech_variant'), name='product_techvariant_unique')],
            },
        ),
    ]
