# Generated by Django 6.0.2 on 2026-03-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='techvariant',
            name='engine_type',
            field=models.CharField(choices=[('NATURALLY_ASPIRATED', 'Атмосферный'), ('TURBO', 'Турбо'), ('SUPERCHARGER', 'Нагнетатель'), ('OTHER', 'Другое')], default='NATURALLY_ASPIRATED', max_length=32),
        ),
        migrations.AddField(
            model_name='techvariant',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Бензин'), ('DIESEL', 'Дизель'), ('LPG', 'Газ (LPG)'), ('CNG', 'Газ (CNG)'), ('ELECTRIC', 'Электро'), ('HYBRID', 'Гибрид')], default='PETROL', max_length=32),
        ),
    ]
