# Generated by Django 6.0.2 on 2026-03-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_techvariant_engine_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techvariant',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_variants', to='catalog.generation'),
        ),
    ]
