# Generated by Django 6.0.2 on 2026-05-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_techvariant_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodystyle',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveConstraint(
            model_name='productvehiclecompatibility',
            name='product_vehicle_unique',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='veh_brand_model_gen_idx',
        ),
        migrations.DeleteModel(
            name='BodyStyle',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.DeleteModel(
            name='ProductVehicleCompatibility',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
