# Generated by Django 6.0.2 on 2026-03-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_site_blocks(apps, schema_editor):
    SiteBlock = apps.get_model('content', 'SiteBlock')
    SiteBlock.objects.get_or_create(
        slug='delivery',
        defaults={'title': 'Условия доставки', 'body': ''},
    )
    SiteBlock.objects.get_or_create(
        slug='about',
        defaults={'title': 'О нас', 'body': ''},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('delivery', 'Доставка'), ('about', 'О нас')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Текстовый блок сайта',
                'verbose_name_plural': 'Текстовые блоки сайта',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_reply', models.TextField(blank=True, default='')),
                ('staff_reply_at', models.DateTimeField(blank=True, null=True)),
                ('staff_reply_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_replied', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_site_blocks, migrations.RunPython.noop),
    ]
