# Generated by Django 6.0.2 on 2026-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_user_verify_siteblock_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
