# Generated by Django 6.0.2 on 2026-03-28 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('brand_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_id', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('body_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tech_variant_id', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, default='', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
