# Generated by Django 6.0.2 on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_expand_order_statuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GarageVehicle',
        ),
    ]
