# Generated by Django 6.0.2 on 2026-05-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_garagevehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VinCheckRequest',
        ),
    ]
